# Generated by Django 5.1.6 on 2025-03-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_table',
            name='category',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
