# Generated by Django 5.1.6 on 2025-03-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_products_table_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_table',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
